server:
  port: ${port}

spring:
  application:
    name: DemoAPI
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://desolate-coast-91481.herokuapp.com/